default:
  # golem variables
  golem_name: whattodo
  golem_version: 0.0.0.9000
  app_prod: no

  ## directory containing the projects
  ## "default" = system.file("extdata", "projects", package = "wheretowork")
  projects: "default"

  ## verbosity
  verbose: false

  ## monitor memory usage
  monitor: false

  ## optimality gap
  solver_gap: 0.1 # 10% from optimality for optimization

  ## time limit (seconds) for generating solutions
  ## i.e. maximum time that users should wait for when generating solutions
  solver_time_limit: 3600 # one hour for generating solution

  ## contact details
  default_project_name: "Richard Schuster"
  default_project_email: "richard.schuster@natureconservancy.ca"

dev:
  golem_wd: !expr here::here()

production:
  app_prod: yes
  projects: "/projects"
  verbose: false
  monitor: false
