default:
  # golem variables
  golem_name: whattodo
  golem_version: 0.0.0.9000
  app_prod: no

  # map variables
  basemap_name: ["Satellite", "Topographic"]
  basemap_key: ["Esri.WorldImagery", "Esri.WorldTopoMap"]

  # default colors
  ## note that color names and codes refer to hard-coded options in leaflet
  ## so you can't simply add new colors how ever you like
  default_color_name: "blue"
  default_color_code: "#37a7d9"

  # colors to display different actions
  ## note that color names and codes refer to hard-coded options in leaflet
  ## so you can't simply add new colors how ever you like
  action_color_names: ["red", "darkred", "lightred", "orange", "beige", "green", "darkgreen", "lightgreen", "blue", "darkblue", "lightblue", "purple", "darkpurple", "pink", "cadetblue", "gray", "lightgray"]
  action_color_codes: ["#d63e2a", "#a23336", "#ff8e7f", "#ef932f", "#ffc990", "#72af26", "#6e7d22", "#bbf970", "#37a7d9", "#00639f", "#8adaff", "#d152b8", "#5a386a", "#ff90e9", "#436978", "#575757", "#a3a3a3"]

production:
  app_prod: yes

dev:
  golem_wd: !expr here::here()
